#! /bin/sh

xsetroot -cursor_name left_ptr
#xinput set-prop 11 "libinput Natural Scrolling Enabled" 1
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Natural Scrolling Enabled"  1
#xinput set-prop "SynPS/2 Synaptics TouchPad" 322 1

#start polybar first

bash ~/.config/polybar/launch.sh &
feh --bg-scale ~/Pictures/Backgrounds/Background.jpg &
#polybar -r main &

#Variables
color0=#3B4252
color1=#5657f5
color2=#5657f5
color4=#D8DEE9

# Make sure sxhkd is always running
while :; do
    if pgrep -x sxhkd > /dev/null; then
        true
    else
        sxhkd &
    fi
    sleep 5
done &

#monitor config
bspc monitor eDP-1 -d 1 2 3 4 5 6 7 8 9 10
#bspc monitor HDMI-1 I II III IV
#bspc monitor DP-1 -d I II III IV


#mouse bindings
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner



bspc config border_width    2
bspc config window_gap      2

bspc config right_padding   2
bspc config left_padding    2
bspc config bottom_padding  2
bspc config top_monocle_padding     0
bspc config right_monocle_padding   0
bspc config left_monocle_padding    0
bspc config bottom_monocle_padding  0

bspc config focused_border_color "$color1"
bspc config normal_border_color "$color0"
bspc config active_border_color  "$color2"
bspc config presel_feedback_color "$color4"


bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a LibreWolf desktop='^2'
bspc rule -a Geany desktop='^4'
bspc rule -a Obsidian desktop='^5'
bspc rule -a Thunderbird desktop='^7'
bspc rule -a Screenkey manage=off

#autostart

#picom -b &
picom --config "$HOME/.config/bspwm/picom.conf" &
lxpolkit &
flameshot &
nm-applet --indicator &
xfce4-power-manager &
blueman-applet &
redshift -l 51:-114 &

#bspc desktop -f ^1
#bash ~/ &
